name: Build

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Build system Dependencies setupしましょ
      - name: Dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget tar
          
      # ソースコードもってきましょ
      - name: Source
        run: |
          wget https://github.com/openwrt/openwrt/archive/refs/tags/v23.05.5.tar.gz
          tar xzvf v23.05.5.tar.gz
          rm v23.05.5.tar.gz

      # feedsをなんとかする
      - name: feeds
        run: |
          mv config v23.05.5/.config
          cd v23.05.5/
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # makeするわよ
      - name: make
        run: |
          echo "準備完了。いくわよ！"
          make -j$(nproc)

      # できたものをArtifactsへ
      - name: Artifacts
        uses: actions/upload-artifact@main
        with:
          name: image
          path: |
            ${{ github.workspace }}/v23.05.5/bin
